class Prettify:
    _prefix = f"\033["

    BLACK = f"{_prefix}0;30m"
    RED = f"{_prefix}0;31m"
    GREEN = f"{_prefix}0;32m"
    BROWN = f"{_prefix}0;33m"
    BLUE = f"{_prefix}0;34m"
    PURPLE = f"{_prefix}0;35m"
    CYAN = f"{_prefix}0;36m"
    LIGHT_GRAY = f"{_prefix}0;37m"
    DARK_GRAY = f"{_prefix}1;30m"
    LIGHT_RED = f"{_prefix}1;31m"
    LIGHT_GREEN = f"{_prefix}1;32m"
    YELLOW = f"{_prefix}1;33m"
    LIGHT_BLUE = f"{_prefix}1;34m"
    LIGHT_PURPLE = f"{_prefix}1;35m"
    LIGHT_CYAN = f"{_prefix}1;36m"
    LIGHT_WHITE = f"{_prefix}1;37m"
    BOLD = f"{_prefix}1m"
    FAINT = f"{_prefix}2m"
    ITALIC = f"{_prefix}3m"
    UNDERLINE = f"{_prefix}4m"
    BLINK = f"{_prefix}5m"
    NEGATIVE = f"{_prefix}7m"
    CROSSED = f"{_prefix}9m"
    END = f"{_prefix}0m"
